conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/set3c/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 31
    intensity: 1.6
  
  noise: 
    name: poisson
    rate: 0.23529 # Alpha: 60
    # rate: 0.15686 # Alpha: 40
    # rate: 0.07843 # Alpha: 20
    # rate: 1
