conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/set3c/

measurement:
  operator:
    name: levin1_blur
  
  noise: 
    name: poisson
    rate: 60
    # rate: 20
    # rate: 10
    # rate: 5

